using System;
using System.Collections.Generic;
using System.Linq;

namespace Morpheus.Rules;

/// <summary>
/// Vocative rules ported from the Python vokativ library
/// https://github.com/mlukasek/vokativ
/// </summary>
public static class VokativRulesFromPython
{
    // Masculine vocative rules from vokativ-master
    // Total rules: 353
    private static readonly Dictionary<string, string> MasculineVocativeRules = new()
    {
        ["treichel"] = "treicheli",
        ["olexandr"] = "olexandre",
        ["reichel"] = "reichle",
        ["kleandr"] = "kleandře",
        ["aksandr"] = "aksandre",
        ["stinus"] = "stine",
        ["abenec"] = "abenče",
        ["upenec"] = "upenče",
        ["atinus"] = "atine",
        ["exandr"] = "exandře",
        ["rtinus"] = "rtine",
        ["ntinus"] = "ntine",
        ["feric"] = "ferici",
        ["khodr"] = "khodre",
        ["xandr"] = "xandre",
        ["yandr"] = "yandre",
        ["deric"] = "derici",
        ["janus"] = "janusi",
        ["zenec"] = "zenče",
        ["tánus"] = "tánusi",
        ["unych"] = "unychu",
        ["lnych"] = "lnychu",
        ["tínus"] = "tíne",
        ["kozel"] = "kozle",
        ["mnych"] = "mnychu",
        ["pytel"] = "pytle",
        ["auzel"] = "auzele",
        ["aanus"] = "aanusi",
        ["dinus"] = "dine",
        ["onych"] = "onychu",
        ["iksey"] = "iksey",
        ["vnych"] = "vnychu",
        ["ynych"] = "ynychu",
        ["gnych"] = "gnychu",
        ["sršeň"] = "sršni",
        ["ceric"] = "cerici",
        ["gintr"] = "gintre",
        ["inych"] = "inychu",
        ["szmek"] = "szmeku",
        ["meric"] = "merici",
        ["hanus"] = "hanusi",
        ["enych"] = "enychu",
        ["datel"] = "datli",
        ["buben"] = "bubne",
        ["ruzel"] = "ruzele",
        ["eandr"] = "eandre",
        ["ošvec"] = "ošvče",
        ["bnych"] = "bnychu",
        ["dmehr"] = "dmehre",
        ["pietr"] = "pietře",
        ["duben"] = "dubne",
        ["rnych"] = "rnychu",
        ["hnych"] = "hnychu",
        ["heric"] = "herici",
        ["vanus"] = "vanusi",
        ["nnych"] = "nnychu",
        ["ppek"] = "ppku",
        ["švec"] = "šveci",
        ["spek"] = "spku",
        ["urec"] = "urče",
        ["órek"] = "órku",
        ["urek"] = "urku",
        ["čamr"] = "čamře",
        ["übek"] = "übku",
        ["yrek"] = "yrku",
        ["sych"] = "sychu",
        ["hlec"] = "hlče",
        ["ypek"] = "ypku",
        ["írek"] = "írku",
        ["írec"] = "írče",
        ["bakr"] = "bakre",
        ["třek"] = "třeku",
        ["ylev"] = "yleve",
        ["mpek"] = "mpku",
        ["ylec"] = "ylče",
        ["klec"] = "klče",
        ["rbek"] = "rbku",
        ["kamr"] = "kamře",
        ["drek"] = "drku",
        ["klev"] = "kleve",
        ["zbek"] = "zbku",
        ["řpek"] = "řpku",
        ["hrek"] = "hrku",
        ["prek"] = "prku",
        ["vlev"] = "vleve",
        ["rlec"] = "rlče",
        ["ürek"] = "ürku",
        ["kbek"] = "kbku",
        ["rlev"] = "rleve",
        ["mlev"] = "mleve",
        ["olev"] = "oleve",
        ["olec"] = "olče",
        ["ábek"] = "ábku",
        ["árec"] = "árče",
        ["árek"] = "árku",
        ["lamr"] = "lamře",
        ["ůbek"] = "ůbku",
        ["irec"] = "irče",
        ["pych"] = "pychu",
        ["llev"] = "lleve",
        ["ůrek"] = "ůrku",
        ["llec"] = "llče",
        ["uzel"] = "uzle",
        ["érek"] = "érku",
        ["jpek"] = "jpku",
        ["fbek"] = "fbku",
        ["enec"] = "enci",
        ["glec"] = "glče",
        ["apek"] = "apku",
        ["bych"] = "bychu",
        ["křek"] = "křeku",
        ["ebek"] = "ebku",
        ["alev"] = "aleve",
        ["učeň"] = "učni",
        ["alec"] = "alče",
        ["úpek"] = "úpku",
        ["stus"] = "ste",
        ["tbek"] = "tbku",
        ["plev"] = "pleve",
        ["dych"] = "dychu",
        ["jágr"] = "jágre",
        ["fotr"] = "fotře",
        ["irek"] = "irku",
        ["ulev"] = "uleve",
        ["hehr"] = "hehre",
        ["ulec"] = "ulče",
        ["opek"] = "opku",
        ["ípek"] = "ípku",
        ["anus"] = "ane",
        ["kpek"] = "kpku",
        ["ýrek"] = "ýrku",
        ["upek"] = "upku",
        ["trek"] = "trku",
        ["trec"] = "trče",
        ["grec"] = "grče",
        ["nbek"] = "nbku",
        ["blev"] = "bleve",
        ["krek"] = "krku",
        ["ibek"] = "ibku",
        ["ílec"] = "ílče",
        ["rpek"] = "rpku",
        ["lych"] = "lychu",
        ["bbek"] = "bbku",
        ["brek"] = "brku",
        ["hbek"] = "hbku",
        ["mbek"] = "mbku",
        ["rajr"] = "rajre",
        ["erec"] = "erče",
        ["šrek"] = "šrku",
        ["tych"] = "tychu",
        ["lpek"] = "lpku",
        ["ýbek"] = "ýbku",
        ["přek"] = "překu",
        ["ipek"] = "ipku",
        ["ietr"] = "ietre",
        ["ěpek"] = "ěpku",
        ["barr"] = "barre",
        ["uděk"] = "uďku",
        ["blec"] = "blče",
        ["yasr"] = "yasee",
        ["erek"] = "erku",
        ["ápek"] = "ápku",
        ["cych"] = "cychu",
        ["rych"] = "rychu",
        ["álec"] = "álče",
        ["sbek"] = "sbku",
        ["jrek"] = "jrku",
        ["nrec"] = "nrče",
        ["gbek"] = "gbku",
        ["dbek"] = "dbku",
        ["ybek"] = "ybku",
        ["ubek"] = "ubku",
        ["eric"] = "ericu",
        ["rrek"] = "rrku",
        ["úrek"] = "úrku",
        ["ánus"] = "áne",
        ["wych"] = "wychu",
        ["vrek"] = "vrku",
        ["sadr"] = "sadre",
        ["elec"] = "elče",
        ["elev"] = "eleve",
        ["mrek"] = "mrku",
        ["wrek"] = "wrku",
        ["ělec"] = "ělče",
        ["ůpek"] = "ůpku",
        ["jlec"] = "jlče",
        ["ébek"] = "ébku",
        ["úbek"] = "úbku",
        ["tlev"] = "tleve",
        ["zejr"] = "zejee",
        ["íbek"] = "íbku",
        ["ilec"] = "ilče",
        ["mitr"] = "mitre",
        ["ilev"] = "ileve",
        ["obek"] = "obku",
        ["épek"] = "épku",
        ["orek"] = "orku",
        ["lbek"] = "lbku",
        ["orec"] = "orče",
        ["batr"] = "batre",
        ["abek"] = "abku",
        ["ksey"] = "kseyi",
        ["arec"] = "arče",
        ["arek"] = "arku",
        ["špek"] = "špku",
        ["ěrek"] = "ěrku",
        ["ěnec"] = "ěnci",
        ["zych"] = "zychu",
        ["mych"] = "mychu",
        ["hamr"] = "hamře",
        ["epek"] = "epku",
        ["óbek"] = "óbku",
        ["cbek"] = "cbku",
        ["sch"] = "schi",
        ["vel"] = "vle",
        ["rel"] = "rle",
        ["hdr"] = "hdr",
        ["jha"] = "jho",
        ["ůha"] = "ůho",
        ["ych"] = "ychi",
        ["lec"] = "leci",
        ["lel"] = "lle",
        ["lev"] = "lve",
        ["ľha"] = "ľho",
        ["cha"] = "cho",
        ["fel"] = "fle",
        ["xha"] = "xho",
        ["ňha"] = "ňho",
        ["del"] = "deli",
        ["lay"] = "layi",
        ["lha"] = "lho",
        ["íha"] = "ího",
        ["gha"] = "gho",
        ["čál"] = "čále",
        ["sál"] = "sále",
        ["ius"] = "ie",
        ["cec"] = "ceci",
        ["uha"] = "uho",
        ["cel"] = "celi",
        ["kál"] = "kále",
        ["áha"] = "áho",
        ["rey"] = "reyi",
        ["rek"] = "reku",
        ["rec"] = "reci",
        ["něk"] = "ňku",
        ["ael"] = "aeli",
        ["nha"] = "nho",
        ["uel"] = "ueli",
        ["tál"] = "tále",
        ["iha"] = "iho",
        ["jel"] = "jle",
        ["bek"] = "beku",
        ["bel"] = "beli",
        ["šel"] = "šeli",
        ["rha"] = "rho",
        ["řel"] = "řeli",
        ["úha"] = "úho",
        ["těk"] = "ťku",
        ["iel"] = "ieli",
        ["íel"] = "íle",
        ["gey"] = "geyi",
        ["gel"] = "geli",
        ["sha"] = "sho",
        ["sel"] = "sle",
        ["kel"] = "kle",
        ["ťál"] = "ťále",
        ["ĺha"] = "ĺho",
        ["otr"] = "otre",
        ["dha"] = "dho",
        ["pha"] = "pho",
        ["yha"] = "yho",
        ["äel"] = "äle",
        ["tha"] = "tho",
        ["yel"] = "yle",
        ["xel"] = "xle",
        ["xey"] = "xeyi",
        ["wel"] = "wle",
        ["ťha"] = "ťho",
        ["amr"] = "amre",
        ["mha"] = "mho",
        ["eel"] = "ele",
        ["čel"] = "čle",
        ["éha"] = "ého",
        ["pel"] = "ple",
        ["pek"] = "peku",
        ["gál"] = "gále",
        ["tel"] = "teli",
        ["aha"] = "aho",
        ["eha"] = "eho",
        ["hel"] = "heli",
        ["zha"] = "zho",
        ["vha"] = "vho",
        ["khr"] = "khre",
        ["oha"] = "oho",
        ["kha"] = "kho",
        ["žel"] = "želi",
        ["gr"] = "gře",
        ["tr"] = "tře",
        ["th"] = "the",
        ["zh"] = "zhi",
        ["zr"] = "zře",
        ["bh"] = "bhe",
        ["mr"] = "mře",
        ["fr"] = "fře",
        ["sr"] = "sře",
        ["sh"] = "shi",
        ["ek"] = "ku",
        ["ec"] = "če",
        ["rr"] = "rře",
        ["ěl"] = "ěli",
        ["dr"] = "dře",
        ["šr"] = "šře",
        ["jr"] = "jře",
        ["cr"] = "cře",
        ["pr"] = "pře",
        ["ph"] = "phe",
        ["iy"] = "iyi",
        ["vr"] = "vře",
        ["är"] = "äře",
        ["ál"] = "áli",
        ["ür"] = "üře",
        ["br"] = "bře",
        ["hr"] = "hře",
        ["ha"] = "hao",
        ["kr"] = "kře",
        ["š"] = "ši",
        ["k"] = "ku",
        ["ě"] = "ě",
        ["a"] = "o",
        ["č"] = "či",
        ["g"] = "gu",
        ["í"] = "í",
        ["ý"] = "ý",
        ["h"] = "hu",
        ["ó"] = "ó",
        ["x"] = "xi",
        ["ž"] = "ži",
        ["ř"] = "ři",
        ["c"] = "ci",
        ["s"] = "si",
        ["ň"] = "ni",
        ["é"] = "é",
        ["i"] = "i",
        ["y"] = "y",
        ["ť"] = "ti",
        ["o"] = "o",
        ["j"] = "ji",
        ["z"] = "zi",
        ["ď"] = "di",
        ["e"] = "e",
        ["ů"] = "ů",
        ["u"] = "u",
        [""] = "e",
    };

    // Gender detection rules from vokativ-master
    // Total rules: 720
    // m = masculine, w = feminine (woman)
    private static readonly Dictionary<string, string> GenderDetectionRules = new()
    {
        ["zendulka"] = "m",
        ["hanička"] = "w",
        ["gustina"] = "w",
        ["havlina"] = "m",
        ["áslavka"] = "m",
        ["helenka"] = "w",
        ["lfriede"] = "w",
        ["justina"] = "w",
        ["halenka"] = "m",
        ["denička"] = "w",
        ["isabela"] = "w",
        ["indulka"] = "m",
        ["obruška"] = "w",
        ["danuška"] = "w",
        ["apolena"] = "w",
        ["johanka"] = "w",
        ["metelka"] = "m",
        ["latuška"] = "w",
        ["xandra"] = "w",
        ["zděnka"] = "w",
        ["kalina"] = "m",
        ["zdenka"] = "w",
        ["zlatka"] = "w",
        ["gelina"] = "w",
        ["vranka"] = "m",
        ["ěruška"] = "w",
        ["iduška"] = "w",
        ["ezanka"] = "m",
        ["švanda"] = "m",
        ["nilica"] = "m",
        ["ilonka"] = "w",
        ["osolda"] = "m",
        ["eodora"] = "w",
        ["dolina"] = "m",
        ["olasta"] = "m",
        ["ichala"] = "w",
        ["álenka"] = "m",
        ["amanda"] = "w",
        ["ulenka"] = "m",
        ["holuša"] = "m",
        ["elenka"] = "m",
        ["zabela"] = "w",
        ["bolina"] = "m",
        ["antina"] = "m",
        ["halica"] = "m",
        ["lilian"] = "w",
        ["dřicha"] = "w",
        ["janina"] = "w",
        ["blanka"] = "w",
        ["estera"] = "w",
        ["nikola"] = "w",
        ["klenka"] = "m",
        ["vadina"] = "m",
        ["ovanda"] = "m",
        ["ědunka"] = "w",
        ["zadina"] = "m",
        ["marika"] = "w",
        ["walica"] = "m",
        ["carmen"] = "w",
        ["teřina"] = "w",
        ["lilija"] = "w",
        ["ětuška"] = "w",
        ["velina"] = "w",
        ["aulina"] = "w",
        ["valina"] = "m",
        ["ardina"] = "w",
        ["volena"] = "m",
        ["brenda"] = "w",
        ["metela"] = "m",
        ["dlenka"] = "m",
        ["iřinka"] = "w",
        ["arleta"] = "w",
        ["estina"] = "w",
        ["kubica"] = "m",
        ["vester"] = "m",
        ["danica"] = "w",
        ["aruška"] = "w",
        ["opolda"] = "w",
        ["polena"] = "m",
        ["malina"] = "m",
        ["slávka"] = "w",
        ["helina"] = "w",
        ["ozděna"] = "m",
        ["ohunka"] = "w",
        ["ivonka"] = "w",
        ["ntiška"] = "w",
        ["karmen"] = "w",
        ["kolena"] = "m",
        ["irenka"] = "w",
        ["uršula"] = "w",
        ["olanta"] = "w",
        ["radina"] = "m",
        ["istina"] = "w",
        ["palica"] = "m",
        ["aluška"] = "m",
        ["rabina"] = "m",
        ["eliška"] = "w",
        ["sandra"] = "w",
        ["etelka"] = "w",
        ["olavka"] = "m",
        ["endula"] = "w",
        ["ahuška"] = "w",
        ["šatava"] = "m",
        ["karin"] = "w",
        ["ělina"] = "m",
        ["hutta"] = "m",
        ["kalla"] = "m",
        ["alica"] = "w",
        ["aněna"] = "m",
        ["palma"] = "m",
        ["ubica"] = "w",
        ["pinka"] = "m",
        ["elina"] = "m",
        ["czina"] = "m",
        ["rbara"] = "w",
        ["atina"] = "m",
        ["solda"] = "w",
        ["lanka"] = "m",
        ["lenka"] = "w",
        ["ytina"] = "m",
        ["odora"] = "m",
        ["elisa"] = "w",
        ["dlina"] = "m",
        ["zlata"] = "w",
        ["ezina"] = "m",
        ["khanh"] = "m",
        ["rnuta"] = "m",
        ["linda"] = "w",
        ["pleva"] = "m",
        ["marta"] = "w",
        ["manta"] = "w",
        ["ndora"] = "m",
        ["eresa"] = "w",
        ["věrka"] = "w",
        ["dinga"] = "m",
        ["sefka"] = "w",
        ["ataša"] = "w",
        ["iběna"] = "w",
        ["činka"] = "m",
        ["alisa"] = "w",
        ["řinka"] = "m",
        ["vinka"] = "m",
        ["dinka"] = "m",
        ["aryta"] = "w",
        ["terna"] = "m",
        ["colle"] = "w",
        ["urina"] = "m",
        ["galia"] = "m",
        ["ozina"] = "m",
        ["vanda"] = "w",
        ["lasta"] = "w",
        ["perna"] = "m",
        ["ngela"] = "w",
        ["arang"] = "m",
        ["asula"] = "m",
        ["žběta"] = "w",
        ["truda"] = "w",
        ["etela"] = "w",
        ["ština"] = "m",
        ["mbora"] = "m",
        ["clava"] = "w",
        ["huong"] = "w",
        ["dejda"] = "w",
        ["raida"] = "m",
        ["ravka"] = "w",
        ["hnila"] = "m",
        ["palla"] = "m",
        ["atica"] = "w",
        ["ilija"] = "m",
        ["lotta"] = "w",
        ["nhung"] = "w",
        ["lvina"] = "w",
        ["obora"] = "m",
        ["rzina"] = "m",
        ["ětina"] = "m",
        ["helma"] = "m",
        ["nošta"] = "w",
        ["šanka"] = "m",
        ["luška"] = "w",
        ["oryna"] = "m",
        ["linka"] = "m",
        ["šárka"] = "w",
        ["dolfa"] = "w",
        ["ysela"] = "m",
        ["cinka"] = "m",
        ["oleva"] = "m",
        ["eszka"] = "w",
        ["kania"] = "m",
        ["vlena"] = "m",
        ["šanca"] = "m",
        ["amela"] = "w",
        ["rauda"] = "w",
        ["hanka"] = "m",
        ["stela"] = "w",
        ["ivera"] = "m",
        ["vlice"] = "m",
        ["riska"] = "w",
        ["nděla"] = "w",
        ["traut"] = "w",
        ["herna"] = "m",
        ["doris"] = "w",
        ["šinka"] = "m",
        ["edina"] = "m",
        ["šenka"] = "w",
        ["minka"] = "m",
        ["uryna"] = "m",
        ["ilica"] = "w",
        ["slava"] = "w",
        ["melen"] = "m",
        ["jenny"] = "w",
        ["avera"] = "m",
        ["onica"] = "w",
        ["jitka"] = "w",
        ["ulawa"] = "m",
        ["olada"] = "m",
        ["halla"] = "m",
        ["asova"] = "w",
        ["enina"] = "m",
        ["tinka"] = "m",
        ["esika"] = "w",
        ["dlena"] = "m",
        ["jurga"] = "m",
        ["enora"] = "m",
        ["jelen"] = "m",
        ["lavka"] = "w",
        ["alada"] = "m",
        ["řiška"] = "w",
        ["lvíra"] = "w",
        ["jasna"] = "w",
        ["řenka"] = "w",
        ["talla"] = "m",
        ["ědina"] = "m",
        ["omana"] = "w",
        ["balla"] = "m",
        ["vitha"] = "m",
        ["agata"] = "w",
        ["katka"] = "w",
        ["verna"] = "m",
        ["rvara"] = "w",
        ["sinka"] = "m",
        ["ibuša"] = "w",
        ["ženka"] = "w",
        ["žanka"] = "m",
        ["zitta"] = "m",
        ["stina"] = "m",
        ["izina"] = "m",
        ["opova"] = "w",
        ["rketa"] = "w",
        ["kvita"] = "m",
        ["citas"] = "w",
        ["apova"] = "w",
        ["nifer"] = "w",
        ["berna"] = "m",
        ["garda"] = "w",
        ["klika"] = "m",
        ["udina"] = "m",
        ["merta"] = "m",
        ["švera"] = "m",
        ["bzina"] = "m",
        ["dvíka"] = "w",
        ["utina"] = "m",
        ["stáňa"] = "m",
        ["ester"] = "w",
        ["vilda"] = "m",
        ["isova"] = "w",
        ["dulka"] = "w",
        ["etina"] = "m",
        ["arika"] = "m",
        ["ubina"] = "m",
        ["huyen"] = "w",
        ["usova"] = "w",
        ["rlota"] = "w",
        ["czyna"] = "m",
        ["laura"] = "w",
        ["nther"] = "m",
        ["atava"] = "w",
        ["thanh"] = "m",
        ["thang"] = "m",
        ["binka"] = "m",
        ["adela"] = "w",
        ["mrska"] = "m",
        ["orota"] = "w",
        ["lbína"] = "w",
        ["zorka"] = "w",
        ["walla"] = "m",
        ["halka"] = "w",
        ["tsova"] = "w",
        ["ulina"] = "m",
        ["emina"] = "m",
        ["iřina"] = "w",
        ["italy"] = "m",
        ["itali"] = "m",
        ["narda"] = "w",
        ["rlina"] = "m",
        ["acola"] = "m",
        ["riena"] = "w",
        ["itina"] = "m",
        ["radka"] = "w",
        ["anina"] = "m",
        ["ipova"] = "w",
        ["evera"] = "m",
        ["pánka"] = "w",
        ["milka"] = "w",
        ["wanda"] = "w",
        ["valla"] = "m",
        ["rinka"] = "m",
        ["oleta"] = "w",
        ["izela"] = "w",
        ["mirka"] = "w",
        ["imara"] = "m",
        ["sitta"] = "m",
        ["rista"] = "w",
        ["ušana"] = "w",
        ["rdina"] = "m",
        ["anata"] = "m",
        ["hlada"] = "m",
        ["gerda"] = "w",
        ["szula"] = "w",
        ["galla"] = "m",
        ["hlena"] = "m",
        ["odina"] = "m",
        ["orica"] = "w",
        ["piva"] = "m",
        ["řada"] = "m",
        ["sova"] = "m",
        ["jína"] = "m",
        ["zala"] = "m",
        ["maja"] = "w",
        ["arla"] = "w",
        ["míra"] = "w",
        ["neša"] = "w",
        ["mela"] = "m",
        ["rska"] = "w",
        ["olha"] = "w",
        ["mana"] = "m",
        ["manh"] = "m",
        ["otta"] = "m",
        ["šala"] = "m",
        ["myla"] = "w",
        ["iama"] = "w",
        ["láva"] = "w",
        ["alsa"] = "m",
        ["bela"] = "m",
        ["čela"] = "m",
        ["elen"] = "w",
        ["ivan"] = "m",
        ["pala"] = "m",
        ["pína"] = "m",
        ["lema"] = "m",
        ["ziva"] = "m",
        ["ěžda"] = "w",
        ["lára"] = "w",
        ["lila"] = "w",
        ["ďala"] = "m",
        ["táňa"] = "w",
        ["věra"] = "w",
        ["iris"] = "w",
        ["heda"] = "w",
        ["nuta"] = "w",
        ["stra"] = "w",
        ["tona"] = "m",
        ["ilya"] = "m",
        ["hang"] = "w",
        ["kala"] = "m",
        ["bora"] = "w",
        ["trun"] = "m",
        ["trud"] = "w",
        ["žina"] = "m",
        ["ilda"] = "w",
        ["řela"] = "m",
        ["kyna"] = "m",
        ["žena"] = "w",
        ["čiva"] = "m",
        ["nila"] = "w",
        ["dita"] = "w",
        ["dith"] = "w",
        ["ežka"] = "w",
        ["bára"] = "w",
        ["těna"] = "m",
        ["vska"] = "w",
        ["tiva"] = "m",
        ["gmar"] = "w",
        ["ikol"] = "w",
        ["zata"] = "w",
        ["illi"] = "m",
        ["illa"] = "m",
        ["lida"] = "m",
        ["indy"] = "w",
        ["gita"] = "w",
        ["sara"] = "w",
        ["vida"] = "m",
        ["nida"] = "m",
        ["esna"] = "w",
        ["reza"] = "w",
        ["eorg"] = "m",
        ["ťala"] = "m",
        ["ylda"] = "w",
        ["peta"] = "m",
        ["elle"] = "w",
        ["ores"] = "w",
        ["jena"] = "w",
        ["tala"] = "m",
        ["tali"] = "w",
        ["beth"] = "w",
        ["běla"] = "w",
        ["beka"] = "w",
        ["šina"] = "m",
        ["eidi"] = "w",
        ["sily"] = "m",
        ["bína"] = "m",
        ["enga"] = "m",
        ["pána"] = "w",
        ["lara"] = "w",
        ["pela"] = "m",
        ["ugda"] = "m",
        ["kira"] = "w",
        ["vela"] = "m",
        ["czna"] = "w",
        ["eňka"] = "w",
        ["lika"] = "w",
        ["tomi"] = "m",
        ["ryla"] = "w",
        ["pova"] = "m",
        ["šeta"] = "m",
        ["nora"] = "w",
        ["vita"] = "w",
        ["nita"] = "w",
        ["rang"] = "w",
        ["rana"] = "m",
        ["dada"] = "m",
        ["tska"] = "w",
        ["eila"] = "w",
        ["nika"] = "w",
        ["žala"] = "m",
        ["atta"] = "m",
        ["rena"] = "w",
        ["urga"] = "w",
        ["inka"] = "w",
        ["leta"] = "m",
        ["gard"] = "w",
        ["daša"] = "w",
        ["lisa"] = "m",
        ["icol"] = "w",
        ["myra"] = "w",
        ["mira"] = "w",
        ["edes"] = "w",
        ["ieda"] = "w",
        ["dala"] = "m",
        ["ěška"] = "w",
        ["acia"] = "m",
        ["sára"] = "w",
        ["llya"] = "m",
        ["koňa"] = "m",
        ["rita"] = "w",
        ["thuy"] = "w",
        ["refa"] = "m",
        ["cina"] = "m",
        ["mada"] = "m",
        ["riam"] = "w",
        ["lore"] = "w",
        ["dela"] = "m",
        ["onga"] = "m",
        ["dora"] = "w",
        ["viga"] = "w",
        ["cína"] = "m",
        ["tnia"] = "m",
        ["mena"] = "w",
        ["iána"] = "w",
        ["tela"] = "m",
        ["tima"] = "w",
        ["iara"] = "w",
        ["šana"] = "m",
        ["ngan"] = "w",
        ["luša"] = "w",
        ["vika"] = "w",
        ["dvan"] = "m",
        ["čada"] = "m",
        ["sala"] = "m",
        ["bada"] = "m",
        ["wada"] = "m",
        ["erta"] = "w",
        ["mice"] = "m",
        ["rída"] = "w",
        ["mala"] = "m",
        ["nesa"] = "w",
        ["loan"] = "w",
        ["etra"] = "w",
        ["míla"] = "w",
        ["zita"] = "w",
        ["linh"] = "w",
        ["řala"] = "m",
        ["kysa"] = "m",
        ["psia"] = "m",
        ["keta"] = "m",
        ["wska"] = "w",
        ["čala"] = "m",
        ["nada"] = "m",
        ["sada"] = "m",
        ["bala"] = "m",
        ["štka"] = "w",
        ["ulma"] = "m",
        ["ther"] = "w",
        ["řina"] = "m",
        ["ylva"] = "w",
        ["pěna"] = "m",
        ["páta"] = "m",
        ["rema"] = "m",
        ["žela"] = "m",
        ["hyna"] = "m",
        ["uyen"] = "m",
        ["zona"] = "m",
        ["aula"] = "w",
        ["avan"] = "m",
        ["liva"] = "m",
        ["diva"] = "m",
        ["ryka"] = "w",
        ["cole"] = "w",
        ["cola"] = "w",
        ["hala"] = "m",
        ["věta"] = "w",
        ["aina"] = "m",
        ["iola"] = "w",
        ["dáša"] = "w",
        ["cvan"] = "m",
        ["vera"] = "w",
        ["mila"] = "w",
        ["zora"] = "w",
        ["wiga"] = "w",
        ["řiva"] = "m",
        ["gela"] = "m",
        ["gnes"] = "w",
        ["iera"] = "w",
        ["unga"] = "m",
        ["ětla"] = "w",
        ["llen"] = "w",
        ["dyna"] = "m",
        ["inge"] = "w",
        ["anka"] = "w",
        ["nata"] = "w",
        ["usan"] = "w",
        ["švan"] = "m",
        ["zela"] = "m",
        ["nska"] = "w",
        ["tana"] = "m",
        ["lien"] = "w",
        ["lies"] = "w",
        ["fela"] = "m",
        ["mája"] = "w",
        ["ilja"] = "m",
        ["běna"] = "m",
        ["ezda"] = "w",
        ["pina"] = "m",
        ["sula"] = "w",
        ["rada"] = "m",
        ["mara"] = "w",
        ["iala"] = "m",
        ["vala"] = "m",
        ["taud"] = "m",
        ["tvan"] = "m",
        ["ilva"] = "w",
        ["eata"] = "w",
        ["olma"] = "m",
        ["idka"] = "w",
        ["vina"] = "m",
        ["ruth"] = "w",
        ["lena"] = "w",
        ["lene"] = "w",
        ["sina"] = "m",
        ["ovan"] = "m",
        ["mida"] = "m",
        ["vira"] = "w",
        ["dzia"] = "m",
        ["rala"] = "m",
        ["smin"] = "w",
        ["vada"] = "m",
        ["čina"] = "m",
        ["ulla"] = "m",
        ["juba"] = "w",
        ["alga"] = "m",
        ["rela"] = "m",
        ["trin"] = "w",
        ["rion"] = "w",
        ["žana"] = "m",
        ["ežda"] = "w",
        ["irma"] = "w",
        ["kvan"] = "m",
        ["rvan"] = "m",
        ["rika"] = "w",
        ["lola"] = "w",
        ["naďa"] = "w",
        ["gala"] = "m",
        ["erna"] = "w",
        ["ryša"] = "w",
        ["ťána"] = "w",
        ["ghia"] = "m",
        ["ines"] = "w",
        ["lída"] = "w",
        ["dena"] = "w",
        ["heta"] = "m",
        ["vien"] = "w",
        ["lska"] = "w",
        ["sica"] = "w",
        ["lma"] = "w",
        ["dne"] = "m",
        ["ďka"] = "w",
        ["ona"] = "w",
        ["ína"] = "w",
        ["iva"] = "w",
        ["sca"] = "w",
        ["ami"] = "m",
        ["ije"] = "m",
        ["eva"] = "w",
        ["éna"] = "w",
        ["jam"] = "w",
        ["lga"] = "w",
        ["ina"] = "w",
        ["óra"] = "w",
        ["ýna"] = "w",
        ["éfa"] = "w",
        ["nca"] = "w",
        ["nga"] = "w",
        ["aud"] = "w",
        ["meg"] = "w",
        ["yen"] = "w",
        ["yet"] = "w",
        ["uja"] = "m",
        ["sťa"] = "w",
        ["mma"] = "w",
        ["vla"] = "w",
        ["éma"] = "w",
        ["ada"] = "w",
        ["uše"] = "w",
        ["ela"] = "w",
        ["ely"] = "m",
        ["git"] = "w",
        ["lla"] = "w",
        ["ály"] = "m",
        ["nna"] = "w",
        ["ala"] = "w",
        ["lli"] = "w",
        ["ĺga"] = "w",
        ["áta"] = "w",
        ["nce"] = "m",
        ["nde"] = "w",
        ["van"] = "w",
        ["oly"] = "m",
        ["tta"] = "w",
        ["oňa"] = "w",
        ["ova"] = "w",
        ["éta"] = "w",
        ["gda"] = "w",
        ["dda"] = "w",
        ["eta"] = "w",
        ["ete"] = "m",
        ["éla"] = "w",
        ["lah"] = "m",
        ["ěja"] = "m",
        ["tsa"] = "w",
        ["ili"] = "w",
        ["thu"] = "w",
        ["tha"] = "w",
        ["ěna"] = "w",
        ["cca"] = "w",
        ["ľga"] = "w",
        ["ase"] = "m",
        ["run"] = "w",
        ["ida"] = "w",
        ["hly"] = "m",
        ["lsa"] = "w",
        ["org"] = "w",
        ["isa"] = "w",
        ["nya"] = "m",
        ["hda"] = "w",
        ["iki"] = "w",
        ["use"] = "m",
        ["lyn"] = "w",
        ["got"] = "w",
        ["ema"] = "w",
        ["ysa"] = "w",
        ["ája"] = "m",
        ["ene"] = "m",
        ["eni"] = "w",
        ["aja"] = "m",
        ["yja"] = "m",
        ["rút"] = "w",
        ["eja"] = "m",
        ["ana"] = "w",
        ["anh"] = "w",
        ["ssa"] = "w",
        ["yna"] = "w",
        ["efa"] = "w",
        ["rid"] = "w",
        ["se"] = "w",
        ["te"] = "w",
        ["ue"] = "w",
        ["ya"] = "w",
        ["aa"] = "w",
        ["ah"] = "w",
        ["ao"] = "w",
        ["ce"] = "w",
        ["du"] = "w",
        ["cy"] = "w",
        ["hi"] = "w",
        ["ia"] = "w",
        ["ie"] = "w",
        ["je"] = "w",
        ["ja"] = "w",
        ["kó"] = "w",
        ["lu"] = "w",
        ["ly"] = "w",
        ["wa"] = "w",
        ["mi"] = "w",
        ["my"] = "w",
        ["ée"] = "w",
        ["ne"] = "w",
        ["oe"] = "w",
        ["oa"] = "w",
        ["ea"] = "w",
        ["á"] = "w",
        [""] = "m",
    };

    // Woman first vs last name detection rules from vokativ-master
    // Total rules: 107
    // f = first name, l = last name
    private static readonly Dictionary<string, string> WomanNameTypeRules = new()
    {
        ["phung"] = "l",
        ["zhang"] = "l",
        ["huong"] = "f",
        ["guyen"] = "l",
        ["ryka"] = "f",
        ["ones"] = "l",
        ["ther"] = "f",
        ["dith"] = "f",
        ["seva"] = "l",
        ["ster"] = "f",
        ["rang"] = "f",
        ["iang"] = "f",
        ["loan"] = "f",
        ["dinh"] = "l",
        ["rinh"] = "l",
        ["yeva"] = "l",
        ["čeva"] = "l",
        ["eeva"] = "l",
        ["hong"] = "f",
        ["reva"] = "l",
        ["kaya"] = "l",
        ["itsa"] = "f",
        ["heva"] = "l",
        ["hang"] = "f",
        ["leva"] = "l",
        ["ieva"] = "l",
        ["deva"] = "l",
        ["tsya"] = "l",
        ["iska"] = "f",
        ["schi"] = "l",
        ["ith"] = "l",
        ["ali"] = "f",
        ["lli"] = "f",
        ["lle"] = "f",
        ["ham"] = "l",
        ["hao"] = "f",
        ["tsa"] = "l",
        ["yma"] = "l",
        ["ska"] = "l",
        ["ole"] = "f",
        ["sen"] = "l",
        ["yka"] = "l",
        ["erg"] = "l",
        ["les"] = "l",
        ["iki"] = "f",
        ["ili"] = "f",
        ["ong"] = "l",
        ["ian"] = "f",
        ["van"] = "f",
        ["fer"] = "f",
        ["hen"] = "l",
        ["gan"] = "f",
        ["ang"] = "l",
        ["san"] = "f",
        ["uan"] = "f",
        ["ini"] = "l",
        ["lyn"] = "f",
        ["lin"] = "l",
        ["lan"] = "f",
        ["mar"] = "f",
        ["ion"] = "f",
        ["ova"] = "l",
        ["uba"] = "f",
        ["thu"] = "f",
        ["yha"] = "l",
        ["le"] = "l",
        ["th"] = "f",
        ["ye"] = "l",
        ["dt"] = "l",
        ["el"] = "f",
        ["en"] = "f",
        ["ei"] = "f",
        ["ee"] = "l",
        ["ze"] = "l",
        ["ey"] = "l",
        ["es"] = "f",
        ["rt"] = "l",
        ["ba"] = "l",
        ["ol"] = "f",
        ["od"] = "l",
        ["oc"] = "f",
        ["ov"] = "f",
        ["hi"] = "f",
        ["mi"] = "f",
        ["kó"] = "f",
        ["un"] = "f",
        ["iy"] = "l",
        ["ai"] = "f",
        ["ah"] = "f",
        ["is"] = "f",
        ["as"] = "f",
        ["im"] = "l",
        ["in"] = "f",
        ["ay"] = "l",
        ["nh"] = "f",
        ["ni"] = "f",
        ["di"] = "f",
        ["ke"] = "l",
        ["d"] = "f",
        ["t"] = "f",
        ["g"] = "f",
        ["é"] = "f",
        ["a"] = "f",
        ["e"] = "f",
        ["m"] = "f",
        ["y"] = "f",
        [""] = "l",
    };

    /// <summary>
    /// Get the matching suffix and its replacement using longest-suffix-first matching
    /// This is the core algorithm from the Python vokativ library
    /// </summary>
    private static (string suffix, string replacement) GetMatchingSuffix(string name, Dictionary<string, string> suffixes)
    {
        // Try suffixes from longest to shortest - CRITICAL for accuracy
        for (int suffixLength = name.Length; suffixLength > 0; suffixLength--)
        {
            var suffix = name.Substring(name.Length - suffixLength);
            if (suffixes.TryGetValue(suffix, out var replacement))
            {
                return (suffix, replacement);
            }
        }
        
        // Return default rule (empty string key)
        return ("", suffixes.GetValueOrDefault("", ""));
    }

    /// <summary>
    /// Transform a masculine name to vocative using the Python vokativ rules
    /// with Czech phonological rule correction for r/ř alternation
    /// </summary>
    public static string TransformMasculineVocative(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        
        var normalizedName = name.ToLowerInvariant();
        var (suffix, replacement) = GetMatchingSuffix(normalizedName, MasculineVocativeRules);
        
        // Apply Czech phonological rule: consonant + r → ř, vowel + r → r
        replacement = ApplyCzechRAlternationRule(normalizedName, suffix, replacement);
        
        // Remove the matched suffix and add the replacement
        var stem = normalizedName.Substring(0, normalizedName.Length - suffix.Length);
        var result = stem + replacement;
        
        // Preserve original casing
        return ApplyCasing(name, result);
    }

    /// <summary>
    /// Transform a feminine first name to vocative using the Python vokativ rules
    /// Simple rule: if ends with 'a', change to 'o', otherwise unchanged
    /// </summary>
    public static string TransformFeminineFirstName(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        
        var normalizedName = name.ToLowerInvariant();
        string result;
        
        if (normalizedName.EndsWith("a"))
        {
            result = normalizedName.Substring(0, normalizedName.Length - 1) + "o";
        }
        else
        {
            result = normalizedName;
        }
        
        // Preserve original casing
        return ApplyCasing(name, result);
    }

    /// <summary>
    /// Transform a feminine last name to vocative using the Python vokativ rules
    /// Simple rule: feminine surnames remain unchanged (nepřechýlená příjmení)
    /// But we should try to restore proper diacritics for Czech surnames
    /// </summary>
    public static string TransformFeminineLastName(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        
        // For feminine surnames, apply diacritic restoration for common patterns
        var result = RestoreFeminineSurnameDiacritics(name);
        
        // Apply proper casing
        return ApplyCasing(name, result);
    }

    /// <summary>
    /// Restore diacritics for feminine surnames based on suffix rules
    /// Only restore diacritics if the input doesn't already contain them
    /// </summary>
    public static string RestoreFeminineSurnameDiacritics(string name)
    {
        var normalized = name.ToLowerInvariant();
        
        // If the name already contains diacritics, don't change it
        // The user input with diacritics is likely the correct form
        if (ContainsDiacritics(name))
        {
            return normalized;
        }
        
        // Only restore diacritics for names without any diacritics
        // Simple suffix-based rules for common Czech feminine surname endings
        if (normalized.EndsWith("va"))
        {
            return normalized.Substring(0, normalized.Length - 2) + "vá";
        }
        else if (normalized.EndsWith("ka"))
        {
            return normalized.Substring(0, normalized.Length - 2) + "ká";
        }
        else if (normalized.EndsWith("na"))
        {
            return normalized.Substring(0, normalized.Length - 2) + "ná";
        }
        
        // If no pattern matches, return as-is
        return normalized;
    }

    /// <summary>
    /// Check if a string contains Czech diacritics
    /// </summary>
    private static bool ContainsDiacritics(string text)
    {
        // Czech diacritics: á, č, ď, é, ě, í, ň, ó, ř, š, ť, ú, ů, ý, ž
        return text.Any(c => "áčďéěíňóřšťúůýžÁČĎÉĚÍŇÓŘŠŤÚŮÝŽ".Contains(c));
    }

    /// <summary>
    /// Detect gender using the Python vokativ rules
    /// </summary>
    public static DetectedGender DetectGender(string name)
    {
        if (string.IsNullOrEmpty(name)) return DetectedGender.Ambiguous;
        
        var normalizedName = name.ToLowerInvariant();
        var (_, gender) = GetMatchingSuffix(normalizedName, GenderDetectionRules);
        
        return gender switch
        {
            "w" => DetectedGender.Feminine,
            "m" => DetectedGender.Masculine,
            _ => DetectedGender.Ambiguous
        };
    }

    /// <summary>
    /// Detect if a feminine name is a first name or last name using the Python vokativ rules
    /// </summary>
    public static bool IsFeminineLastName(string name)
    {
        if (string.IsNullOrEmpty(name)) return false;
        
        var normalizedName = name.ToLowerInvariant();
        var (_, nameType) = GetMatchingSuffix(normalizedName, WomanNameTypeRules);
        
        return nameType == "l"; // 'l' means last name, 'f' means first name
    }

    /// <summary>
    /// Apply Czech phonological rule for r/ř alternation
    /// Rule: consonant + r → ř, vowel + r → r (no alternation)
    /// </summary>
    private static string ApplyCzechRAlternationRule(string word, string matchedSuffix, string replacement)
    {
        // Only apply to replacements ending in 're' or 'ře'
        if (!replacement.EndsWith("re") && !replacement.EndsWith("ře"))
            return replacement;

        // Check if the matched suffix ends in 'r'
        if (!matchedSuffix.EndsWith("r"))
            return replacement;

        // Find the character immediately before 'r' in the matched suffix within the original word
        var suffixStartPosition = word.Length - matchedSuffix.Length;
        var rPositionInSuffix = matchedSuffix.LastIndexOf('r');
        var rPositionInWord = suffixStartPosition + rPositionInSuffix;
        
        // Check if there's a character before the 'r' in the original word
        if (rPositionInWord <= 0)
            return replacement; // r is at the beginning, use default

        // Get the character immediately before 'r' in the original word
        var charBeforeR = word[rPositionInWord - 1];

        // Check if it's a consonant or vowel
        bool isVowel = "aeiouyáéěíóúůý".Contains(charBeforeR);

        // Heuristic: treat vowel + 'j' before 'r' as a vowel environment (diphthong), e.g., Štejr → Štejre
        // If the character before 'r' is 'j' and the character before 'j' is a vowel, prefer 're'
        if (!isVowel && charBeforeR == 'j' && rPositionInWord - 1 > 0)
        {
            var charBeforeJ = word[rPositionInWord - 2];
            if ("aeiouyáéěíóúůý".Contains(charBeforeJ))
            {
                isVowel = true;
            }
        }

        if (isVowel)
        {
            // Vowel + r → no alternation, should end in 're'
            return replacement.EndsWith("ře") ? replacement.Replace("ře", "re") : replacement;
        }
        else
        {
            // Consonant + r → alternation, should end in 'ře'
            return replacement.EndsWith("re") ? replacement.Replace("re", "ře") : replacement;
        }
    }

    /// <summary>
    /// Apply casing from the original name to the result
    /// </summary>
    private static string ApplyCasing(string original, string result)
    {
        if (string.IsNullOrEmpty(original) || string.IsNullOrEmpty(result)) return result;

        // All uppercase original
        if (original.ToUpperInvariant() == original)
        {
            return result.ToUpperInvariant();
        }

        // Smart capitalization: if original is all lowercase (like user typed names),
        // still capitalize the first letter for proper names
        if (original.ToLowerInvariant() == original && char.IsLetter(original[0]))
        {
            if (result.Length == 1) return result.ToUpperInvariant();
            return char.ToUpperInvariant(result[0]) + result.Substring(1).ToLowerInvariant();
        }

        // Title-case: first letter uppercase, rest preserved as-is
        if (char.IsLetter(original[0]) && char.IsUpper(original[0]))
        {
            if (result.Length == 1) return result.ToUpperInvariant();
            return char.ToUpperInvariant(result[0]) + result.Substring(1);
        }

        // Default: lower-case
        return result.ToLowerInvariant();
    }
}
