<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.18.0" />
    <PackageReference Include="Microsoft.ML.Tokenizers" Version="2.0.0-preview.25373.1" />
    <PackageReference Include="Tokenizers.DotNet" Version="1.2.1" />
    <PackageReference Include="Tokenizers.DotNet.runtime.win-x64" Version="1.2.1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="..\name_classifier.onnx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="..\custom-bpe-tokenizer.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="name_classifier.onnx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="custom-bpe-tokenizer.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="name_classifier.onnx.data">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
